<?php

namespace App\Filament\App\Resources\Studio\StudioResource\Pages;

use App\Filament\App\Resources\Studio\StudioResource;
use App\Filament\Common\Schemas\Studio\StudioFormSchema;
use App\Models\Enums\ProductTypeCast;
use App\Models\Product\Product;
use App\Models\Project\Project;
use App\Models\Subscription\Plan;
use App\Services\MoneyService\Money;
use Filament\Actions;
use Filament\Forms\Components\Wizard;
use Filament\Resources\Pages\CreateRecord;
use Filament\Forms\Form;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\HtmlString;

class CreateStudio extends CreateRecord
{
    use CreateRecord\Concerns\HasWizard,StudioFormSchema;
    protected static string $resource = StudioResource::class;
    public ?Plan $plan = null;
    protected static bool $canCreateAnother = false;



    public function form(Form $form): Form
    {
        return $form
            ->schema(fn() => $this->getStudioFormSchema());
    }



    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = filament()->auth()->user()->id;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


}
