<?php

namespace App\Filament\App\Resources\UserResource\Pages;

use App\Filament\App\Resources\UserResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListUsers extends ListRecords
{
    protected static string $resource = UserResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }


    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->redirect(self::$resource::getUrl('view',['record' => filament()->auth()->user()->id]));
    }


}
