<?php

namespace Database\Seeders;

use App\Casts\PublishableStatusCast;
use App\Models\Content\CaseStudy;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductionCaseStudySeeder extends Seeder
{
    public function run(): void
    {
        $caseStudies = [
            [
                'title' => 'Commerce Product Line Rollout Framework',
                'description' => 'Built a repeatable go-to-market structure to launch multiple niche ecommerce products with clear category positioning.',
                'content' => '<h2>Business Objective</h2><p>Scale product count while keeping delivery quality and launch speed high.</p><h2>Execution Model</h2><p>Delivered category-focused products with distinct positioning, copy, and buyer journeys for each niche segment.</p><h2>Portfolio Outcome</h2><p>Enabled consistent releases, lower operational overhead, and clearer product-market segmentation.</p>',
                'image' => 'https://images.unsplash.com/photo-1556742393-d75f468bfcb0?w=1200',
                'client' => 'Mintreu Commerce Program',
                'industry' => 'Digital Commerce Products',
                'duration' => '8 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'MySQL', 'Redis'],
                'challenge' => 'Adding more storefront products usually causes backend duplication, operational drift, and release delays.',
                'solution' => 'Standardized product operations and focused differentiation on frontend UX, category controls, and offer strategy.',
                'results' => json_encode([
                    ['value' => '20+', 'label' => 'Commerce Product Variants'],
                    ['value' => '1', 'label' => 'Unified Operations Model'],
                    ['value' => '-58%', 'label' => 'Estimated Backend Maintenance Load'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => true,
            ],
            [
                'title' => 'Fashion & Lifestyle Conversion Program',
                'description' => 'Optimized fashion and lifestyle-focused product experiences for higher conversion and stronger repeat purchase behavior.',
                'content' => '<h2>Business Objective</h2><p>Improve conversion quality for category-personalized storefronts in fashion and lifestyle segments.</p><h2>Execution Model</h2><p>Applied audience-specific merchandising paths, cleaner checkout journeys, and segment-first catalog controls while keeping backend contracts unchanged.</p><h2>Portfolio Outcome</h2><p>Improved storefront efficiency without adding backend systems.</p>',
                'image' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200',
                'client' => 'Mintreu Fashion Vertical',
                'industry' => 'Fashion & Lifestyle Ecommerce',
                'duration' => '6 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'MySQL'],
                'challenge' => 'Generic storefront behavior underperformed for highly specific fashion/lifestyle buyer intent.',
                'solution' => 'Introduced category-locked frontend flows and segment-specific merchandising logic within the same API-driven architecture.',
                'results' => json_encode([
                    ['value' => '+34%', 'label' => 'Checkout Conversion'],
                    ['value' => '+29%', 'label' => 'Repeat Purchase Share'],
                    ['value' => '-23%', 'label' => 'Bounce Rate'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => true,
            ],
            [
                'title' => 'Home, Specialty & Seasonal Catalog Expansion',
                'description' => 'Expanded product portfolio into furniture, toys, wellness, gadget, and specialty niches with a unified launch system.',
                'content' => '<h2>Business Objective</h2><p>Launch many vertical products fast while preserving operational consistency.</p><h2>Execution Model</h2><p>Standardized inventory and order workflows while differentiating each storefront by niche taxonomy, copy strategy, and buyer-specific UX.</p><h2>Portfolio Outcome</h2><p>Enabled rapid vertical expansion with release confidence.</p>',
                'image' => 'https://images.unsplash.com/photo-1556742031-c6961e8560b0?w=1200',
                'client' => 'Mintreu Commerce Growth',
                'industry' => 'Multi-Vertical Ecommerce',
                'duration' => '7 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'Redis'],
                'challenge' => 'Niche storefront launches were constrained by backend dependencies and repetitive implementation tasks.',
                'solution' => 'Moved differentiation to frontend product strategy and standardized core operations for faster release velocity.',
                'results' => json_encode([
                    ['value' => '12+', 'label' => 'Additional Niche Product Launches'],
                    ['value' => '3.2x', 'label' => 'Faster Rollout Cadence'],
                    ['value' => '99.9%', 'label' => 'Operational Consistency'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => true,
            ],
            [
                'title' => 'Support Product Family Standardization',
                'description' => 'Created a structured support product family across ticket, message, live chat, and AI-assisted use cases.',
                'content' => '<h2>Business Objective</h2><p>Offer multiple support products for different buyer needs without fragmenting operations.</p><h2>Execution Model</h2><p>Standardized support workflows and delivered product-specific frontend experiences for each support mode.</p><h2>Portfolio Outcome</h2><p>Consistent support operations with flexible product packaging.</p>',
                'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200',
                'client' => 'Mintreu Support Program',
                'industry' => 'Support SaaS Products',
                'duration' => '6 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'MySQL', 'Redis'],
                'challenge' => 'Different support offers typically create disconnected tooling and analytics gaps.',
                'solution' => 'Implemented one support API contract for all offerings and split differentiation at the frontend product layer.',
                'results' => json_encode([
                    ['value' => '10+', 'label' => 'Support Product Variants'],
                    ['value' => '4', 'label' => 'Offer Modes Covered'],
                    ['value' => '-47%', 'label' => 'Ops Complexity Growth'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => true,
            ],
            [
                'title' => 'AI + Human Support Efficiency Lift',
                'description' => 'Improved support delivery quality by combining AI-assisted triage with ticket and real-time support workflows.',
                'content' => '<h2>Business Objective</h2><p>Increase support throughput while preserving response quality.</p><h2>Execution Model</h2><p>Integrated AI-assisted suggestions, queue prioritization, and real-time escalation paths in a unified support architecture.</p><h2>Portfolio Outcome</h2><p>Higher productivity for support teams and better customer response metrics.</p>',
                'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200',
                'client' => 'Mintreu Service Operations',
                'industry' => 'AI-Assisted Support',
                'duration' => '5 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'Redis', 'OpenAI'],
                'challenge' => 'Repetitive support load consumed agent capacity and slowed high-priority issue handling.',
                'solution' => 'Added AI-assisted workflows and escalation governance on top of standardized support APIs.',
                'results' => json_encode([
                    ['value' => '+42%', 'label' => 'Agent Throughput'],
                    ['value' => '-36%', 'label' => 'First Response Time'],
                    ['value' => '4.8/5', 'label' => 'Support Satisfaction'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => false,
            ],
            [
                'title' => 'Commerce + Support Bundle Revenue Strategy',
                'description' => 'Linked commerce and support product families into one revenue strategy for stronger recurring conversion.',
                'content' => '<h2>Business Objective</h2><p>Increase recurring revenue by connecting frontend product sales to API subscription journeys.</p><h2>Execution Model</h2><p>Packaged commerce and support product lines as a coordinated portfolio with clear upgrade and expansion pathways.</p><h2>Portfolio Outcome</h2><p>Higher deal quality and improved subscription conversion performance.</p>',
                'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200',
                'client' => 'Mintreu Commercial Team',
                'industry' => 'SaaS Revenue Strategy',
                'duration' => '6 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'MySQL'],
                'challenge' => 'One-time product sales did not consistently move buyers into recurring API subscriptions.',
                'solution' => 'Introduced portfolio-level bundle positioning and subscription-aware onboarding across product families.',
                'results' => json_encode([
                    ['value' => '+31%', 'label' => 'Recurring Conversion Rate'],
                    ['value' => '+24%', 'label' => 'Average Deal Value'],
                    ['value' => '2', 'label' => 'API Product Families Unified'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => false,
            ],
            [
                'title' => 'Boutique Checkout Recovery Playbook',
                'description' => 'Recovered abandoned checkouts for boutique storefronts with intent-focused UX flow and checkout simplification.',
                'content' => '<h2>Business Objective</h2><p>Capture more paid orders from high-intent fashion traffic.</p><h2>Execution Model</h2><p>Optimized product detail flow, trust signals, and reduced checkout steps across boutique-focused storefront products.</p><h2>Portfolio Outcome</h2><p>Higher order completion with better conversion consistency during promotions.</p>',
                'image' => 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200',
                'client' => 'Mintreu Boutique Portfolio',
                'industry' => 'Boutique Ecommerce',
                'duration' => '4 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'Redis'],
                'challenge' => 'High product page engagement was not converting into completed orders.',
                'solution' => 'Rebuilt checkout micro-flow and merchandising handoff to remove friction before payment.',
                'results' => json_encode([
                    ['value' => '+28%', 'label' => 'Order Completion Rate'],
                    ['value' => '-33%', 'label' => 'Checkout Abandonment'],
                    ['value' => '+19%', 'label' => 'Revenue Per Visitor'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => true,
            ],
            [
                'title' => 'Furniture Catalog High-Ticket Conversion Lift',
                'description' => 'Improved high-ticket furniture purchasing behavior with guided category journeys and trust-led product pages.',
                'content' => '<h2>Business Objective</h2><p>Increase AOV and paid order quality for home and furniture products.</p><h2>Execution Model</h2><p>Introduced category-specific discovery, intent-based filters, and conversion-safe checkout flows.</p><h2>Portfolio Outcome</h2><p>Higher high-ticket order confidence and measurable AOV growth.</p>',
                'image' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200',
                'client' => 'Mintreu Home Commerce Line',
                'industry' => 'Furniture & Home Store',
                'duration' => '5 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'MySQL'],
                'challenge' => 'Visitors browsed deeply but delayed purchase decisions on high-value items.',
                'solution' => 'Aligned catalog UX with high-ticket buying behavior and strengthened trust checkpoints.',
                'results' => json_encode([
                    ['value' => '+31%', 'label' => 'Average Order Value'],
                    ['value' => '+22%', 'label' => 'Paid Orders'],
                    ['value' => '-17%', 'label' => 'Decision-to-Purchase Time'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => true,
            ],
            [
                'title' => 'Toy Store Seasonal Order Surge Stabilization',
                'description' => 'Handled seasonal toy demand spikes while maintaining fast checkout and stable order capture.',
                'content' => '<h2>Business Objective</h2><p>Protect conversion during seasonal traffic peaks and flash campaigns.</p><h2>Execution Model</h2><p>Used category-locked storefront strategy with API-backed performance tuning and queue-friendly purchase flow.</p><h2>Portfolio Outcome</h2><p>Traffic surges converted into stable paid orders instead of performance drop-offs.</p>',
                'image' => 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1200',
                'client' => 'Mintreu Toys Vertical',
                'industry' => 'Kids & Toy Store',
                'duration' => '4 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'Redis'],
                'challenge' => 'Campaign peaks risked missed orders due to load variance and checkout latency.',
                'solution' => 'Applied seasonal-safe storefront patterns and API limit controls for stable conversion.',
                'results' => json_encode([
                    ['value' => '3.4x', 'label' => 'Traffic Handling Capacity'],
                    ['value' => '+26%', 'label' => 'Paid Orders in Peak Window'],
                    ['value' => '99.93%', 'label' => 'Checkout Availability'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => false,
            ],
            [
                'title' => 'Women Category Store Retention Engine',
                'description' => 'Built a repeat-purchase funnel for women category stores with segment-personalized journeys.',
                'content' => '<h2>Business Objective</h2><p>Improve repeat orders and monthly revenue predictability.</p><h2>Execution Model</h2><p>Optimized customer dashboard journeys, lifecycle nudges, and category-first merchandising flow.</p><h2>Portfolio Outcome</h2><p>Stronger customer retention and healthier recurring purchase behavior.</p>',
                'image' => 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1200',
                'client' => 'Mintreu Women Commerce Portfolio',
                'industry' => 'Women Category Store',
                'duration' => '6 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'MySQL'],
                'challenge' => 'Strong acquisition performance was not translating to repeat buying.',
                'solution' => 'Introduced retention-first UX and post-purchase customer dashboard strategy.',
                'results' => json_encode([
                    ['value' => '+37%', 'label' => 'Repeat Order Rate'],
                    ['value' => '+24%', 'label' => 'LTV Uplift'],
                    ['value' => '-21%', 'label' => '30-Day Churn'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => false,
            ],
            [
                'title' => 'D2C Multi-Store Operations Standardization',
                'description' => 'Standardized operations across multiple niche ecommerce storefronts with one commerce API core.',
                'content' => '<h2>Business Objective</h2><p>Scale product sales across several storefront brands with lean operations.</p><h2>Execution Model</h2><p>Centralized backend logic and launched differentiated frontends by niche persona and category focus.</p><h2>Portfolio Outcome</h2><p>Faster launches and predictable maintenance cost while growing catalog breadth.</p>',
                'image' => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200',
                'client' => 'Mintreu Commerce Ops',
                'industry' => 'D2C Ecommerce',
                'duration' => '9 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'Redis'],
                'challenge' => 'Managing multiple store products usually increases support and release complexity.',
                'solution' => 'Standardized backend contracts and made differentiation fully frontend-product driven.',
                'results' => json_encode([
                    ['value' => '12', 'label' => 'Stores Managed in One Model'],
                    ['value' => '-49%', 'label' => 'Operational Overhead Growth'],
                    ['value' => '2.7x', 'label' => 'Launch Velocity'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => false,
            ],
            [
                'title' => 'Live Chat Assisted Order Conversion Desk',
                'description' => 'Mapped pre-sales chat journeys to conversion events and increased order capture from support interactions.',
                'content' => '<h2>Business Objective</h2><p>Convert pre-sales chat traffic into paid ecommerce orders.</p><h2>Execution Model</h2><p>Connected live support flows with purchase intent signals and product recommendation events.</p><h2>Portfolio Outcome</h2><p>Support interactions became a measurable revenue channel.</p>',
                'image' => 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200',
                'client' => 'Mintreu Support + Commerce Program',
                'industry' => 'Conversational Commerce',
                'duration' => '5 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'Redis'],
                'challenge' => 'High chat volume was not linked to purchase events or sales attribution.',
                'solution' => 'Built conversion-aware support flow and tracked assisted revenue from chat operations.',
                'results' => json_encode([
                    ['value' => '+18%', 'label' => 'Assisted Conversion Rate'],
                    ['value' => '+21%', 'label' => 'Chat-to-Order Revenue'],
                    ['value' => '-27%', 'label' => 'Unresolved Pre-Sales Queries'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => false,
            ],
            [
                'title' => 'Support Desk Renewal & Re-Subscription Loop',
                'description' => 'Improved subscription renewals by integrating lifecycle nudges and reactivation paths in support product experiences.',
                'content' => '<h2>Business Objective</h2><p>Increase renewals and recover at-risk subscriptions.</p><h2>Execution Model</h2><p>Added renewal prompts, account health indicators, and context-aware re-subscription flow.</p><h2>Portfolio Outcome</h2><p>Stronger recurring retention and better subscription continuity.</p>',
                'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200',
                'client' => 'Mintreu Recurring Revenue Program',
                'industry' => 'SaaS Subscription Retention',
                'duration' => '4 weeks',
                'technologies' => ['Laravel', 'Nuxt', 'MySQL'],
                'challenge' => 'Churn and delayed renewals reduced recurring revenue reliability.',
                'solution' => 'Designed proactive lifecycle messaging and low-friction reactivation paths.',
                'results' => json_encode([
                    ['value' => '+27%', 'label' => 'Renewal Rate'],
                    ['value' => '+14%', 'label' => 'Recovered Subscriptions'],
                    ['value' => '-19%', 'label' => 'Voluntary Churn'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => false,
            ],
            [
                'title' => 'Portfolio Funnel Optimization for Order Capture',
                'description' => 'Reframed homepage and case-study narrative to move more visitors into qualified inquiry and paid order flow.',
                'content' => '<h2>Business Objective</h2><p>Use mintreu.com portfolio as a conversion engine, not only a showcase.</p><h2>Execution Model</h2><p>Aligned product pages, projects, and case studies with direct sales intent: clear outcomes, trust signals, and action pathways.</p><h2>Portfolio Outcome</h2><p>Better lead quality and higher order-intent conversations.</p>',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200',
                'client' => 'Mintreu Growth Team',
                'industry' => 'B2B Product Sales',
                'duration' => '3 weeks',
                'technologies' => ['Nuxt', 'Laravel', 'Analytics'],
                'challenge' => 'Traffic and engagement existed, but conversion to order-oriented conversations was inconsistent.',
                'solution' => 'Rewrote portfolio story around outcomes, ROI metrics, and product-to-order pathways.',
                'results' => json_encode([
                    ['value' => '+32%', 'label' => 'Qualified Inquiries'],
                    ['value' => '+23%', 'label' => 'Demo-to-Order Rate'],
                    ['value' => '+17%', 'label' => 'Pipeline Velocity'],
                ]),
                'status' => PublishableStatusCast::PUBLISHED,
                'featured' => true,
            ],
        ];

        $allowedSlugs = collect($caseStudies)
            ->map(fn (array $caseStudy): string => Str::slug($caseStudy['title']))
            ->all();

        CaseStudy::query()->whereNotIn('slug', $allowedSlugs)->delete();

        foreach ($caseStudies as $caseStudyData) {
            CaseStudy::updateOrCreate(
                ['slug' => Str::slug($caseStudyData['title'])],
                $caseStudyData
            );
        }
    }
}
