<?php

namespace App\Filament\Common\Resources\Studio\StudioResource\Pages;

use App\Filament\Common\Resources\Studio\StudioResource;
use App\Filament\Common\Schemas\Studio\StudioFormSchema;
use App\Models\Product\Product;
use App\Models\Subscription\Plan;
use Filament\Forms\Form;
use Filament\Resources\Pages\CreateRecord;

class CreateStudio extends CreateRecord
{
    use CreateRecord\Concerns\HasWizard,StudioFormSchema;
    protected static string $resource = StudioResource::class;
    public ?Plan $plan = null;
    protected static bool $canCreateAnother = false;

    protected ?Product $product = null;
    protected $plan_id;
    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->product = Product::firstWhere('id',request()->query('product_id'));
        $this->plan_id = request()->query('plan_id');
        if (!is_null($this->product))
        {
            $this->form->fill([
                'product_id' => $this->product->id,
                'plan_id' => $this->plan_id
            ]);
        }


    }


    public function form(Form $form): Form
    {
        return $form
            ->schema(fn() => $this->getStudioFormSchema());
    }



//    protected function mutateFormDataBeforeCreate(array $data): array
//    {
//        $data['user_id'] = filament()->auth()->user()->id;
//        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
//    }



}
