<?php

namespace App\Filament\Common\Resources\Studio\StudioResource\Pages;

use App\Filament\Common\Resources\Studio\StudioResource;
use Filament\Actions;
use Filament\Infolists\Components\Grid;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\RepeatableEntry;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\Split;
use Filament\Infolists\Components\Tabs;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

class ViewStudio extends ViewRecord
{
    protected static string $resource = StudioResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\EditAction::make(),
            Actions\Action::make('view_auth')
                ->fillForm(fn() => $this->record->toArray())
                ->infolist([
                    TextEntry::make('key')->label('Key')->copyable()->columnSpan(2),
                    TextEntry::make('secret')->label('Secret')->copyable()->columnSpan(2),
                ]),

            Actions\Action::make('view_licence')
                ->fillForm(fn() => $this->record->toArray())
                ->infolist([
                    TextEntry::make('serial')->label('Serial')
                ])
        ];
    }


    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub
        self::$title = 'View '. $this->record->name;
    }


    public function infolist(Infolist $infolist): Infolist
    {
        return parent::infolist($infolist)
            ->schema([


                Section::make('Studio Details')

                    ->aside()
                    ->schema([
                        TextEntry::make('name')->label('Studio Name')
                            ->inlineLabel()
                            ->hiddenLabel()
                            ->size(TextEntry\TextEntrySize::Large)
                            ->color('primary')
                            ->weight('bold')->size('lg'),
                        TextEntry::make('version')->label('Version')->hiddenLabel()->badge()->inlineLabel(),
                        //TextEntry::make('url')->label('URL'),
                        TextEntry::make('domain')
                            ->label('Domain')->columnSpan(3)
                            ->icon('heroicon-m-globe-alt')
                            ->url(fn($state) => $state,true)
                            ->inlineLabel(),


                        TextEntry::make('channel')->label('Channel')->inlineLabel()->badge(),

                        TextEntry::make('platform')->label('Platform')->inlineLabel()->badge(),
                    ]),



                Section::make('Service or Products')
                    ->aside()
                    ->schema([

                        TextEntry::make('product.name')
                            ->label('Product')
                            ->icon('heroicon-m-cube')
                            ->visible(fn ($record) => $record->product !== null),

                        TextEntry::make('product.type')->badge()->hiddenLabel(),
                        TextEntry::make('product.short_desc')
                            ->label(__('About'))
                            ->columnSpanFull()->alignJustify(),


                    ]),



                Section::make('Plan & Subscription')
                    ->aside()
                    ->columns()
                    ->columnSpanFull()
                    ->schema([
                        TextEntry::make('plan.name')
                            ->label('Plan')
                            ->icon('heroicon-m-clipboard-document-check')
                            ->inlineLabel()
                            ->size(TextEntry\TextEntrySize::Medium)
                            ->default('--no plan found--'),

                        TextEntry::make('plan.per_month_limit')
                            ->label(__('Monthly Limit'))->badge()->suffix(' Requests')
                            ->inlineLabel()
                            ,

                        IconEntry::make('subscription.is_active')
                            ->label('Subscribe')
                            ->icon('heroicon-m-receipt-refund')
                            ->default('--no subscription found--'),


                        TextEntry::make('expire_on')->label('Expires On')->dateTime()->badge()->color('danger'),
                        IconEntry::make('is_active')->label('Active')->boolean(),
                        IconEntry::make('is_trial')->label('Trial')->boolean(),
                        TextEntry::make('trial_ends_at')->label('Trial Ends At')->dateTime()->badge()->color('warning'),

                        RepeatableEntry::make('plan.features')->label(__('Features')),
                    ]),










                TextEntry::make('host_type')
                    ->label('Host Type')
                    ->visible(fn ($record) => $record->host_type !== null),

                TextEntry::make('host_id')
                    ->label('Host ID')
                    ->visible(fn ($record) => $record->host_id !== null),


                TextEntry::make('metadata')
                    ->label('Metadata')
                    ->formatStateUsing(fn ($state) => json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES))
                    ->columnSpanFull()
                    ->copyable(),


            ]);
    }
}
